[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer']

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'php artisan storage:link'
]

[start]
cmd = 'php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php -S 0.0.0.0:$PORT -t public'
